### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Romz24** [AGraber/samp-037-compat-fix#2]
Why do I get an error when compiling?
**OS:** ubuntu 14.04 64bit

![image](https://user-images.githubusercontent.com/2458113/43167030-104e76f6-8fa1-11e8-9d95-f5917fe61291.png)

**Comment by AGraber** [comment]
which version of gcc are you using?

**Comment by Romz24** [comment]
gcc version 4.8.5

**Comment by AGraber** [comment]
Sorry but I can't fix that for now. Next release of samp-compat may feature a standalone plugin for all versions (which I'm already working on).

I'll release a minor version right now to upload statically compiled binaries, which should work on older versions if that's what you're looking for.
